### PR TITLE
some additional libraries needed or getting started nb

### PR DESCRIPTION
**Pull request by JohnGriffiths**
Just some small things that came up when the `getting_started` nb. 

Also in the intro notebook:

- Typo `from File_IO import ioa` (should be `io`  I think )
- Several instances of `TypeError: DynamicFilter() takes from 4 to 6 positional arguments but 7 were given`

Super excited about this library. Looking forward to getting stuck in!

### CODE REVIEW

**Comment by JohnGriffiths** [comment]
Got a few more fixes and also some suggestions. @emmaspeh are you at fNIRS conf? Do you want do a quick coding sess?

**Comment by emmaspeh** [comment]
> Got a few more fixes and also some suggestions. @emmaspeh are you at fNIRS conf? Do you want do a quick coding sess?

Yes, I am at the conference now, we could meet up to discuss these issues! @JohnGriffiths

**Comment by JohnGriffiths** [comment]
Great. I am sat at the bottom of the stairs in main auditorium.

**Comment by emmaspeh** [comment]
We will come down after the session ends.

**Comment by emmaspeh** [comment]
Made updates that seem to fix the DynamicFilter issue - will be down shortly.

**Comment by emmaspeh** [comment]
@JohnGriffiths Where are you now? We are downstairs.

**Comment by JohnGriffiths** [comment]
ibid. i'm in the conference room, at the bottom of the stairs.

**Pull request merged**
